export const styles = {
  container: {
    maxWidth: "600px",
    margin: "0 auto",
    minHeight: "100vh",
    backgroundColor: "#fff",
    boxShadow: "0 0 20px rgba(0,0,0,0.05)",
    paddingBottom: "80px", // Aumentado para não cobrir o anúncio fixo
  },
  header: (color: string) => ({
    backgroundColor: color,
    padding: "25px 20px",
    color: "white",
    borderBottomLeftRadius: "24px",
    borderBottomRightRadius: "24px",
    transition: "background-color 0.3s ease",
    textAlign: "center" as const,
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
  }),
  title: {
    margin: "0 0 15px 0",
    fontSize: "28px",
    fontWeight: "800",
  },
  select: {
    padding: "12px 20px",
    borderRadius: "30px",
    border: "none",
    fontSize: "16px",
    width: "100%",
    maxWidth: "320px",
    cursor: "pointer",
    fontWeight: "bold",
    backgroundColor: "rgba(255,255,255,0.9)",
    color: "#333",
    outline: "none",
    boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
  },
  tabBar: {
    display: "flex",
    justifyContent: "space-evenly",
    padding: "15px 10px",
    backgroundColor: "white",
    position: "sticky" as const,
    top: 0,
    zIndex: 100,
    borderBottom: "1px solid #f0f0f0",
  },
  tab: (active: boolean, color: string) => ({
    padding: "10px 16px",
    borderRadius: "20px",
    cursor: "pointer",
    backgroundColor: active ? `${color}15` : "transparent",
    color: active ? color : "#888",
    fontWeight: active ? "700" : "500",
    border: "none",
    transition: "all 0.2s",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    fontSize: "12px",
    gap: "4px",
  }),
  icon: {
    fontSize: "24px",
    marginBottom: "2px",
  },
  content: {
    padding: "20px",
    animation: "fadeIn 0.5s ease",
  },
  ball: (color: string, isMatch = false, isMiss = false, size = "40px") => ({
    width: size,
    height: size,
    borderRadius: "50%",
    backgroundColor: isMatch ? color : isMiss ? "#f0f0f0" : color,
    color: isMatch ? "white" : isMiss ? "#ccc" : "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    margin: "4px",
    fontSize: parseInt(size) * 0.4 + "px",
    boxShadow: isMiss ? "none" : "0 2px 4px rgba(0,0,0,0.2)",
    border: isMatch ? "3px solid #FFD700" : "none",
    transform: isMatch ? "scale(1.1)" : "scale(1)",
    transition: "transform 0.2s",
  }),
  selectableBall: (selected: boolean, color: string) => ({
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    border: selected ? `2px solid ${color}` : "1px solid #e0e0e0",
    backgroundColor: selected ? color : "white",
    color: selected ? "white" : "#666",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    margin: "5px",
    cursor: "pointer",
    fontSize: "14px",
    transition: "all 0.2s ease",
    userSelect: "none" as const,
    boxShadow: selected ? `0 3px 8px ${color}60` : "none",
  }),
  ballsContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "center",
    gap: "8px",
    marginTop: "20px",
    marginBottom: "20px",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "20px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.05)",
    marginBottom: "20px",
    border: "1px solid #f5f5f5",
  },
  winnerCard: (color: string) => ({
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "20px",
    boxShadow: `0 4px 15px ${color}40`,
    marginBottom: "20px",
    border: `2px solid ${color}`,
    position: "relative" as const,
  }),
  button: (color: string, disabled = false, outline = false) => ({
    backgroundColor: disabled ? "#ccc" : outline ? "transparent" : color,
    color: disabled ? "white" : outline ? color : "white",
    border: outline ? `2px solid ${color}` : "none",
    padding: "12px 20px",
    borderRadius: "12px",
    cursor: disabled ? "not-allowed" : "pointer",
    fontWeight: "bold",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    flex: 1,
    boxShadow: (disabled || outline) ? "none" : "0 4px 6px rgba(0,0,0,0.1)",
    transition: "transform 0.1s active",
  }),
  statItem: {
    display: "flex",
    alignItems: "center",
    marginBottom: "12px",
  },
  statLabel: {
    width: "30px",
    fontWeight: "bold" as const,
    color: "#555",
  },
  statBarBg: {
    flex: 1,
    height: "10px",
    backgroundColor: "#eee",
    borderRadius: "5px",
    margin: "0 10px",
    overflow: "hidden",
  },
  statBarFill: (percentage: number, color: string) => ({
    height: "100%",
    width: `${percentage}%`,
    backgroundColor: color,
    borderRadius: "5px",
  }),
  statValue: {
    width: "40px",
    textAlign: "right" as const,
    fontSize: "12px",
    color: "#888",
  },
  badge: {
    backgroundColor: "#eee",
    padding: "4px 8px",
    borderRadius: "6px",
    fontSize: "12px",
    color: "#666",
    marginTop: "10px",
    display: "inline-block",
  },
  infoText: {
    color: "#666",
    lineHeight: "1.5",
    fontSize: "14px",
    textAlign: "center" as const,
  },
  aiBox: {
    background: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
    padding: "20px",
    borderRadius: "16px",
    color: "white",
    marginTop: "20px",
    textAlign: "center" as const,
    boxShadow: "0 4px 15px rgba(253, 160, 133, 0.4)",
  },
  summaryBox: (color: string) => ({
    backgroundColor: `${color}10`,
    border: `1px solid ${color}30`,
    borderRadius: "16px",
    padding: "15px",
    marginBottom: "20px",
  }),
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "5px",
  },
  gridContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "center",
    margin: "10px -5px",
  },
  // --- Estilos de Anúncios ---
  adBannerFixed: {
    position: "fixed" as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: "60px",
    backgroundColor: "#f7f7f7",
    borderTop: "1px solid #e0e0e0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    boxShadow: "0 -2px 10px rgba(0,0,0,0.05)",
  },
  adBannerInline: {
    width: "100%",
    maxWidth: "100%",
    height: "100px", // Altura padrão banner mobile grande
    backgroundColor: "#f0f0f0",
    border: "1px dashed #ccc",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    margin: "20px 0",
    overflow: "hidden",
  },
  adLabel: {
    fontSize: "10px",
    color: "#999",
    textTransform: "uppercase" as const,
    letterSpacing: "1px",
    marginBottom: "4px",
  },
  adContent: {
    color: "#bbb",
    fontWeight: "bold" as const,
    fontSize: "14px",
  }
};
